server:
  http:
    addr: 0.0.0.0:9999
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9007
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/kratos-mall
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
